name: CI-checkstyle-java-lint
on: [pull_request]
jobs:
  lint:
    runs-on: self-hosted
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      # Runs a set of commands using the runners shell
      - name: Run linter
        run: |
          cd backend/
          ./gradlew task checkstyleMain
          ./gradlew task checkstyleTest
