name: CI-java-test-coverage
on: [pull_request]
jobs:
  lint:
    runs-on: self-hosted
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2s
        with:
          java-version: '17'
          distribution: 'temurin'
      # Runs a set of commands using the runners shell
      - name: Run test coverage
        run: |
          cd backend/
          ./gradlew task test
      - name: Add coverage to PR
        id: jacoco
        uses: madrapps/jacoco-report@v1.2
