name: TS-prettier-and-linter
on: [pull_request]
jobs:
  lint:
    runs-on: self-hosted
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      # Runs a set of commands using the runners shell
      - name: Run linter and prettier
        run: |
          cd frontend/
          rm package-lock.json
          npm install
          npm run lint
          RESULT=$?
          [ $RESULT -ne 0 ] && echo "lint failed" && exit 1
          exit 0
  prittier:
    runs-on: self-hosted
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      # Runs a set of commands using the runners shell
      - name: Run linter and prettier
        run: |
          cd frontend/
          rm package-lock.json
          npm install
          npx prettier --check .
          RESULT=$?
          [ $RESULT -ne 0 ] && echo "Code is not pretty" && exit 1
          exit 0
