name: 'coverage'
on: [pull_request]
jobs:
  coverage:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          working-directory: frontend
