name: 'coverage'
on: [pull_request]
jobs:
  coverage:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Go to frontend
        run: |
          cd frontend/
          rm package-lock.json
      - uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          package-manager: npm
