name: ts-coverage
on: [pull_request]
jobs:
  jest:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: Go to frontend
        run: |
          cd frontend/
          rm package-lock.json
          npm install
      - uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          working-directory: frontend
